# Generated by Django 3.2.9 on 2021-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_postblog_blog_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='postblog',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
