# Generated by Django 3.2.9 on 2021-12-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20211201_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.ForeignKey(default='Uncategorized', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='blogapp.categories'),
        ),
    ]
